# Generated by Django 5.2.6 on 2025-10-17 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='data',
            field=models.FileField(default=1, upload_to='uploads'),
            preserve_default=False,
        ),
    ]
