# Generated by Django 5.2.6 on 2025-10-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_alter_file_parent_folder_alter_folder_parent_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
    ]
