# Generated by Django 5.2.6 on 2025-10-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='media_type',
            field=models.CharField(default='image', max_length=10),
            preserve_default=False,
        ),
    ]
