# Generated by Django 5.2.6 on 2025-10-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_file_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtype',
            name='description',
            field=models.CharField(default='A tag', max_length=300),
            preserve_default=False,
        ),
    ]
