# Generated by Django 5.2.6 on 2025-10-24 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_tagtype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='assets.file'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='assets.tagtype'),
        ),
    ]
