# Generated by Django 5.2.6 on 2025-10-25 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_alter_tag_file_alter_tag_type'),
        ('users', '0003_alter_employee_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='data',
        ),
        migrations.RemoveField(
            model_name='file',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='file',
            name='size',
        ),
        migrations.AlterField(
            model_name='file',
            name='date_modified',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0, editable=False)),
                ('filetype', models.CharField(max_length=5)),
                ('media_type', models.CharField(max_length=10)),
                ('data', models.FileField(upload_to='uploads')),
                ('version', models.PositiveSmallIntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.employee')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='currentFile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='assets.fileversion'),
        ),
    ]
