# Generated by Django 5.2.6 on 2025-10-25 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_remove_file_data_remove_file_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='currentFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.fileversion'),
        ),
    ]
