# Generated by Django 5.2.6 on 2025-10-25 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_file_currentfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='currentFile',
        ),
        migrations.RemoveField(
            model_name='file',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='file',
            name='filetype',
        ),
        migrations.RemoveField(
            model_name='file',
            name='media_type',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.AddField(
            model_name='fileversion',
            name='original_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.file'),
        ),
    ]
