# Generated by Django 5.2.6 on 2025-10-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_remove_file_currentfile_remove_file_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileversion',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
