# Generated by Django 5.2.6 on 2025-10-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_fileversion_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileversion',
            name='filetype',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='media_type',
            field=models.CharField(max_length=30),
        ),
    ]
