# Generated by Django 5.2.6 on 2025-11-13 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_alter_folder_parent_folder'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('file', 'type')},
        ),
    ]
