# Generated by Django 5.2.6 on 2025-11-13 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_alter_tag_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='file_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='assets.fileversion'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('file_version', 'type')},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='file',
        ),
        
    ]
