# Generated by Django 5.2.6 on 2025-11-14 03:36

import assets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_alter_tag_unique_together_tag_file_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagtype',
            name='color',
            field=models.CharField(default='#00db2c', max_length=7, validators=[assets.models.validate_hex]),
        ),
    ]
