import type { Metadata } from "next";
import { Roboto, Reddit_Mono } from "next/font/google";
import "./globals.css";
import { Provider } from "@/components/ui/provider"

const redditMono = Reddit_Mono({
  variable: "--font-reddit-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DAM-N",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="no-touch" suppressHydrationWarning>
      <body className={`${redditMono.variable} ${roboto.variable}`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
